### ISSUE TITLE
There are many broken links in the notebooks

### ISSUE THREAD

**Issue by brian-rose** [brian-rose/ClimateLaboratoryBook#3]
This may take a while to clean up. The notebooks have a number of broken "internal" links to other notebooks -- a legacy of the old structure in the `ClimateModeling_courseware` repository.

Obviously I need to either get rid of the links or update them so they point to something.

**Comment by brian-rose** [comment]
Fixed a lot of these... there may still be some in notebooks that we didn't use in class Spring 2020.

**Comment by brian-rose** [comment]
Update, a few more of these have been fixed but I need to go through and do a careful check, especially in the "Advanced" notebooks (which have not been used in class in this format yet).

**Comment by zmoon** [comment]
Here are some current link checker results:
![image](https://user-images.githubusercontent.com/15079414/118267554-428dae00-b48a-11eb-844d-3a767b9edd7b.png)
not visible in the image are more of the open-sans in the CSS

**Comment by brian-rose** [comment]
@zmoon thanks! How did you generate this? Does the tool also check internal links (i.e. links to other pages within `https://brian-rose.github.io/ClimateLaboratoryBook/`)?

**Comment by brian-rose** [comment]
Sorry, spoke too soon. There are clearly some internal links on that list.

**Comment by zmoon** [comment]
I used this website: https://www.drlinkcheck.com/ (free as long as website isn't huge)

But also Sphinx can check links with `make linkcheck` (though I've never tried this)

I don't know what happened to the RRTM page, it seems like it is down. But they have RRTMG at least on GH now it looks like: https://github.com/AER-RC

**Comment by brian-rose** [comment]
Thanks.

I just learned that I can do
```
jupyter-book build . --builder linkcheck 
```
and it flags all kind of stuff including redirects and in-page anchors.

**Comment by brian-rose** [comment]
Partially addressed in https://github.com/brian-rose/ClimateLaboratoryBook/commit/5ddae86d7e958abd5e6f8789157a5e6688c2028a

Still more to clean up.

**Comment by brian-rose** [comment]
#24 fixes the remaining broken links, and adds a GitHub action to run the link checker periodically, as well as on all future PRs.
